### ISSUE TITLE
sputnikdao2: after BountyDone proposal is approved, claims not clearing as expected

### ISSUE THREAD

**Issue by mikedotexe** [near-daos/sputnik-dao-contract#27] opened 2021-07-05 00:20 UTC
Looks like there are a couple ways to approach bounties with sputnikdao2. The way I've been playing with goes as follows:

1. An `AddBounty` proposal is created.
2. It's approved by the council.
3. A non-council user Alice claims the bounty.
4. A `BountyDone` proposal is created for the bounty from step 1.
5. A council member approves the `BountyDone` proposal, firing off the payout.
6. I expect to see that Alice has no bounty claims, but she still shows the same one.

Handy script to run or copy/paste using NEAR CLI:

```sh
#!/bin/sh

# Change these to your account ids
./build.sh
export CONTRACT_ID=sputnikdao2.mike.testnet
export CONTRACT_PARENT=mike.testnet

# Redo account (if contract already exists)
near delete $CONTRACT_ID $CONTRACT_PARENT
near create-account $CONTRACT_ID --masterAccount $CONTRACT_PARENT

# Set up
near deploy $CONTRACT_ID --wasmFile ~/near/sputnik-dao-contract/sputnikdao2/res/sputnikdao2.wasm
export COUNCIL='["'$CONTRACT_ID'"]'
near call $CONTRACT_ID new '{"config": {"name": "genesis2", "purpose": "test", "metadata": ""}, "policy": '$COUNCIL'}' --accountId $CONTRACT_ID

# Add proposal for a Transfer kind that pays out 19 NEAR
near call $CONTRACT_ID add_proposal '{"proposal": {"description": "test bounty", "kind": {"AddBounty": {"bounty": {"description": "do the thing", "token": "near", "amount": "19000000000000000000000000", "times": 3, "max_deadline": "1925376849430593581"}}}}}' --accountId $CONTRACT_PARENT --amount 1

# Show error when a user tries to vote along with log
near call $CONTRACT_ID act_proposal '{"id": 0, "action": "VoteApprove"}' --accountId $CONTRACT_ID

# Someone claims the bounty
near call $CONTRACT_ID bounty_claim '{"id": 0, "deadline": "1925376849430593581"}' --accountId $CONTRACT_PARENT --amount 1

# Show bounty claims
near view $CONTRACT_ID get_bounty_claims '{"account_id": "'$CONTRACT_PARENT'"}'

# Add BountyDone proposal done
near call $CONTRACT_ID add_proposal '{"proposal": {"description": "test bounty done", "kind": {"BountyDone": {"bounty_id": 0, "receiver_id": "'$CONTRACT_PARENT'"}}}}' --accountId $CONTRACT_PARENT --amount 1

# Vote it in
near call $CONTRACT_ID act_proposal '{"id": 1, "action": "VoteApprove"}' --accountId $CONTRACT_ID --gas 300000000000000

# See how many now. Expect it to be empty but it's not
near view $CONTRACT_ID get_bounty_claims '{"account_id": "'$CONTRACT_PARENT'"}'
```

Here's the bottom part of the output, which shows that it's not clearing:

```
…
View call: sputnikdao2.mike.testnet.get_bounty_claims({"account_id": "mike.testnet"})
[
  {
    bounty_id: 0,
    start_time: '1625444816555618690',
    deadline: '1925376849430593581',
    completed: false
  }
]
Scheduling a call: sputnikdao2.mike.testnet.add_proposal({"proposal": {"description": "test bounty done", "kind": {"BountyDone": {"bounty_id": 0, "receiver_id": "mike.testnet"}}}}) with attached 1 NEAR
Transaction Id 5Koeb389XEt7kcHq99tSy5TGSNpy1Tr6bj4g16fWBArG
To see the transaction in the transaction explorer, please open this url in your browser
https://explorer.testnet.near.org/transactions/5Koeb389XEt7kcHq99tSy5TGSNpy1Tr6bj4g16fWBArG
1
Scheduling a call: sputnikdao2.mike.testnet.act_proposal({"id": 1, "action": "VoteApprove"})
Transaction Id Bp4jFu31v9XcXZQdWvcjaVmWWTdbLcBCMwG85bBiLTVr
To see the transaction in the transaction explorer, please open this url in your browser
https://explorer.testnet.near.org/transactions/Bp4jFu31v9XcXZQdWvcjaVmWWTdbLcBCMwG85bBiLTVr
''
View call: sputnikdao2.mike.testnet.get_bounty_claims({"account_id": "mike.testnet"})
[
  {
    bounty_id: 0,
    start_time: '1625444816555618690',
    deadline: '1925376849430593581',
    completed: false
  }
]
```

**Comment by ctindogaru** [comment] 2021-12-21 12:53
I've just tested this while working on https://github.com/near-daos/sputnik-dao-contract/pull/80 and I could reproduce. The bounties are cleared on `bounty_giveup` but not on `bounty_done`. Looks like a bug.

Will work on a fix, thanks for reporting it!

**Comment by ctindogaru** [comment] 2021-12-21 14:04
This is now fixed in https://github.com/near-daos/sputnik-dao-contract/issues/27. More precisely, commit https://github.com/near-daos/sputnik-dao-contract/pull/80/commits/6bddfad906fc24c9dc1e5e1d7fe681f6f2827b1a

**Comment by mikedotexe** [comment] 2022-01-10 17:39
Updated the script I had in the description to use the `token` "near" instead of the empty string, which is how it used to be.
Also added max gas to the final `VoteApprove` as that wasn't enough now. Thanks, Constantin, looking into the PR now

**Comment by ctindogaru** [comment] 2022-01-11 08:39
Thanks Mike.

Closing the issue as this is now fixed.

**Closed by ctindogaru** 2022-01-11 08:39 UTC
